"""empty message

Revision ID: 206594167c34
Revises: 5170082a66c8
Create Date: 2014-08-11 03:08:39.104000

"""

# revision identifiers, used by Alembic.
revision = '206594167c34'
down_revision = '5170082a66c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musician',
    sa.Column('m_id', sa.Integer(), nullable=False),
    sa.Column('m_category', sa.String(length=20), nullable=True),
    sa.Column('m_major', sa.String(length=20), nullable=True),
    sa.Column('m_phrase', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('m_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musician')
    ### end Alembic commands ###
