"""empty message

Revision ID: 294b53f8753e
Revises: None
Create Date: 2014-08-05 23:05:19.035000

"""

# revision identifiers, used by Alembic.
revision = '294b53f8753e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
