"""empty message

Revision ID: 312bd1833a63
Revises: 429e4e3b5854
Create Date: 2014-08-14 22:23:53.936000

"""

# revision identifiers, used by Alembic.
revision = '312bd1833a63'
down_revision = '429e4e3b5854'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userid', sa.String(length=15), nullable=True))
    op.drop_column('user', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'userid')
    ### end Alembic commands ###
