"""empty message

Revision ID: 339c1e718dce
Revises: 312bd1833a63
Create Date: 2014-08-28 00:54:25.594000

"""

# revision identifiers, used by Alembic.
revision = '339c1e718dce'
down_revision = '312bd1833a63'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musician_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musician_major',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'musician', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column(u'musician', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column(u'musician', sa.Column('major_id', sa.Integer(), nullable=True))
    op.add_column(u'musician', sa.Column('phrase', sa.String(length=50), nullable=True))
    op.drop_column(u'musician', 'm_major')
    op.drop_column(u'musician', 'm_category')
    op.drop_column(u'musician', 'm_id')
    op.drop_column(u'musician', 'm_phrase')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'musician', sa.Column('m_phrase', mysql.VARCHAR(length=50), nullable=True))
    op.add_column(u'musician', sa.Column('m_id', mysql.INTEGER(display_width=11), nullable=False))
    op.add_column(u'musician', sa.Column('m_category', mysql.VARCHAR(length=20), nullable=True))
    op.add_column(u'musician', sa.Column('m_major', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column(u'musician', 'phrase')
    op.drop_column(u'musician', 'major_id')
    op.drop_column(u'musician', 'id')
    op.drop_column(u'musician', 'category_id')
    op.drop_table('musician_major')
    op.drop_table('musician_category')
    ### end Alembic commands ###
