"""empty message

Revision ID: 5800d66330f7
Revises: 34ffe21c48bc
Create Date: 2014-08-29 01:30:51.856000

"""

# revision identifiers, used by Alembic.
revision = '5800d66330f7'
down_revision = '34ffe21c48bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('awards', 'name')
    ### end Alembic commands ###
